In [2]:
import numpy as np

In [5]:
#Crear Arreglo de 3 a mi edad
matrizEdad = np.array(range(3,29))

In [6]:
matrizEdad

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28])

In [16]:
#Crear Arreglo de 0 a 4
matrizNumeros = np.array(range(0,5))

In [8]:
#Crear Arreglo Junto
matrizNumerosJuntos = np.append(matrizNumeros,matrizNumeros)

In [9]:
matrizNumerosJuntos

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [15]:
#Ordenar Arreglos
matrizNumerosJuntos.sort()
matrizNumerosJuntos

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])